import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";

const root = process.cwd();
const docsDir = join(root, "docs");

function run(command, args) {
  try {
    return execFileSync(command, args, { cwd: root, encoding: "utf8" }).trim();
  } catch {
    return "확인 필요";
  }
}

function readJson(path) {
  const fullPath = join(root, path);
  if (!existsSync(fullPath)) return null;
  try {
    return JSON.parse(readFileSync(fullPath, "utf8"));
  } catch {
    return null;
  }
}

function fileStatus(path) {
  const fullPath = join(root, path);
  if (!existsSync(fullPath)) return { path, status: "missing", bytes: 0 };
  return { path, status: "present", bytes: statSync(fullPath).size };
}

const pkg = readJson("package.json") ?? {};
const linkResult = readJson("LINK_VERIFICATION_RESULT.json") ?? {};
const branch = run("git", ["branch", "--show-current"]);
const commit = run("git", ["rev-parse", "--short", "HEAD"]);
const status = (run("git", ["status", "--short"]) || "clean").replace(/\r?\n/g, "; ");
const recentCommits = run("git", ["log", "--oneline", "-8"])
  .split(/\r?\n/)
  .filter(Boolean);

const releaseHighlights = [
  "비회원도 홈, 검색, 카테고리, 상세, 마이/정책 화면을 확인할 수 있고, 로그인은 찜한 특가와 관심 카테고리 이어보기에만 선택적으로 사용됩니다.",
  "홈과 카테고리는 검증된 실제 상품 상세 URL 또는 공식 혜택 상세 URL 중심으로 탐색되며, 구매 이동은 내부 /go 경로를 거쳐 외부 판매처로 열립니다.",
  "무료 혜택, 쿠폰, 앱테크, 마감 임박, 인기 특가, 카테고리별 탐색, 가격 알림 준비 UI가 V1.0 출시 후보 범위에 포함됩니다.",
  "Play Console/App Store Connect 입력값, 수동 제출 체크리스트, 실기기 QA 매니페스트, 스토어 스크린샷 매니페스트, 출시 인수인계 리포트가 자동 생성됩니다."
];

const userFacingNotes = [
  "오늘 볼 특가와 무료 혜택을 더 빠르게 찾을 수 있도록 홈 탐색을 정리했습니다.",
  "상품 상세와 구매 전 확인 화면에서 판매처 도메인, 가격 변동 가능성, 신고 경로를 확인할 수 있습니다.",
  "찜, 최근 본 상품, 관심 카테고리, 가격 알림 후보를 기기 저장과 계정 동기화 구조로 이어볼 수 있습니다.",
  "구매 링크는 앱이 직접 결제하지 않고 외부 판매처 또는 공식 혜택 페이지로 이동합니다."
];

const operatorNotes = [
  "신규 상품/혜택은 검색 결과, 대표몰, 커뮤니티 글 단독 URL이 아니라 실제 상품 상세 URL 또는 공식 혜택 상세 URL을 사용해야 합니다.",
  "스토어 제출 전 `npm run store:manual:doctor`, `npm run store:packet:doctor`, `npm run release:doctor`를 통과시켜야 합니다.",
  "signed AAB 업로드, 공개 개인정보처리방침/고객지원 URL 확인, 실기기 QA, 스크린샷 업로드, OAuth Provider 설정은 자동 완료 처리 금지 항목입니다.",
  "keystore 비밀번호, OAuth client secret, Supabase service-role key, .env 값, tester password, 주문/결제/주소 정보는 릴리즈 노트와 이슈에 기록하지 않습니다."
];

const verificationArtifacts = [
  fileStatus("docs/release-evidence.md"),
  fileStatus("docs/STORE_CONSOLE_FIELDS.md"),
  fileStatus("docs/STORE_MANUAL_CHECKLIST.md"),
  fileStatus("docs/STORE_HANDOFF_REPORT.md"),
  fileStatus("docs/STORE_SUBMISSION_REPORT.md"),
  fileStatus("docs/DEVICE_QA_MANIFEST.md"),
  fileStatus("docs/STORE_SCREENSHOT_MANIFEST.md"),
  fileStatus("docs/link-coverage-report.md")
];

const payload = {
  generatedBy: "npm run release:notes",
  branch,
  commit,
  workingTree: status,
  version: pkg.version ?? "unknown",
  appName: "할인도사",
  packageName: "com.halindosa.app",
  linkCoverage: {
    visibleDeals: linkResult.visibleDeals ?? null,
    passedDirectLinks: linkResult.passedDirectLinks ?? null,
    verificationTargets: linkResult.verificationTargets ?? null,
    manualReviewNeeded: linkResult.manualReviewNeeded ?? null
  },
  releaseHighlights,
  userFacingNotes,
  operatorNotes,
  verificationArtifacts,
  recentCommits,
  manualWorkThatMustNotBeFaked: [
    "Do not claim Play Console or App Store Connect submission has passed from this file.",
    "Do not claim real-device QA passed unless docs/device-qa-record-template.md has been filled with actual device evidence.",
    "Do not record secrets, tester credentials, order/payment data, or private console screenshots."
  ]
};

const markdown = [
  "# 할인도사 Release Notes",
  "",
  "This non-secret release note summarizes the current V1.0 launch candidate for reviewers, QA, and store submission handoff. It does not prove external console upload, real-device QA, or public-domain reachability.",
  "",
  "## Release Candidate",
  "",
  `- Generated by: \`npm run release:notes\``,
  `- Branch: \`${branch}\``,
  `- Commit: \`${commit}\``,
  `- Working tree: ${status}`,
  `- App version: \`${payload.version}\``,
  "- App name: 할인도사",
  "- Package / Bundle ID: `com.halindosa.app`",
  "",
  "## User-Facing Release Notes",
  "",
  ...userFacingNotes.map((note) => `- ${note}`),
  "",
  "## Launch Candidate Highlights",
  "",
  ...releaseHighlights.map((note) => `- ${note}`),
  "",
  "## Link And Data Readiness Snapshot",
  "",
  `- Visible curated deals: ${payload.linkCoverage.visibleDeals ?? "unknown"}`,
  `- Direct product or official benefit links: ${payload.linkCoverage.passedDirectLinks ?? "unknown"}/${payload.linkCoverage.verificationTargets ?? "unknown"}`,
  `- Manual review needed: ${payload.linkCoverage.manualReviewNeeded ?? "unknown"}`,
  "",
  "## Operator Notes",
  "",
  ...operatorNotes.map((note) => `- ${note}`),
  "",
  "## Verification Artifacts",
  "",
  "| File | Status |",
  "| --- | --- |",
  ...verificationArtifacts.map((item) => `| \`${item.path}\` | ${item.status}${item.bytes ? ` (${item.bytes} bytes)` : ""} |`),
  "",
  "## Recent Commits",
  "",
  ...recentCommits.map((line) => `- \`${line}\``),
  "",
  "## Manual Work That Must Not Be Faked",
  "",
  ...payload.manualWorkThatMustNotBeFaked.map((note) => `- ${note}`),
  ""
].join("\n");

mkdirSync(docsDir, { recursive: true });
writeFileSync(join(root, "RELEASE_NOTES.json"), `${JSON.stringify(payload, null, 2)}\n`, "utf8");
writeFileSync(join(root, "RELEASE_NOTES.md"), markdown, "utf8");
writeFileSync(join(docsDir, "RELEASE_NOTES.md"), markdown, "utf8");

console.log("Release notes written: RELEASE_NOTES.json, RELEASE_NOTES.md, and docs/RELEASE_NOTES.md");
